Traceback (most recent call last):
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "E:\programas\Anaconda\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from dwave.system import DWaveSampler

sampler = DWaveSampler(solver=dict(topology__type='chimera'))

response = sampler.sample(
    bqm, num_reads=10,
    annealing_time=10,
    auto_scale=False,
    answer_mode='raw',
    label='Prueba_DWaveSampler'
    )
print(response)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
File [1;32mc:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\dwave\system\samplers\dwave_sampler.py:206[0m, in [0;36mDWaveSampler._get_solver[1;34m(self, refresh, penalty)[0m
[0;32m    205[0m [38;5;28;01mtry[39;00m:
[1;32m--> 206[0m     [38;5;28;01mreturn[39;00m [43msolvers[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m
[0;32m    207[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIndexError[39;00m:

[1;31mIndexError[0m: list index out of range

During handling of the above exception, another exception occurred:

[1;31mSolverNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[12], line 3[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdwave[39;00m[38;5;21;01m.[39;00m[38;5;21;01msystem[39;00m [38;5;28;01mimport[39;00m DWaveSampler
[1;32m----> 3[0m sampler [38;5;241m=[39m [43mDWaveSampler[49m[43m([49m[43msolver[49m[38;5;241;43m=[39;49m[38;5;28;43mdict[39;49m[43m([49m[43mtopology__type[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mchimera[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m)[49m
[0;32m      5[0m response [38;5;241m=[39m sampler[38;5;241m.[39msample(
[0;32m      6[0m     bqm, num_reads[38;5;241m=[39m[38;5;241m10[39m,
[0;32m      7[0m     annealing_time[38;5;241m=[39m[38;5;241m10[39m,
[1;32m   (...)[0m
[0;32m     10[0m     label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPrueba_DWaveSampler[39m[38;5;124m'[39m
[0;32m     11[0m     )
[0;32m     12[0m [38;5;28mprint[39m(response)

File [1;32mc:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\dwave\system\samplers\dwave_sampler.py:185[0m, in [0;36mDWaveSampler.__init__[1;34m(self, failover, retry_interval, **config)[0m
[0;32m    182[0m [38;5;28mself[39m[38;5;241m.[39m_solver_penalty [38;5;241m=[39m defaultdict([38;5;28mint[39m)
[0;32m    184[0m [38;5;28mself[39m[38;5;241m.[39mclient [38;5;241m=[39m Client[38;5;241m.[39mfrom_config([38;5;241m*[39m[38;5;241m*[39mconfig)
[1;32m--> 185[0m [38;5;28mself[39m[38;5;241m.[39msolver [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_solver[49m[43m([49m[43mpenalty[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_solver_penalty[49m[43m)[49m

File [1;32mc:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\dwave\system\samplers\dwave_sampler.py:208[0m, in [0;36mDWaveSampler._get_solver[1;34m(self, refresh, penalty)[0m
[0;32m    206[0m     [38;5;28;01mreturn[39;00m solvers[[38;5;241m0[39m]
[0;32m    207[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIndexError[39;00m:
[1;32m--> 208[0m     [38;5;28;01mraise[39;00m SolverNotFoundError([38;5;124m"[39m[38;5;124mSolver with the requested features not available[39m[38;5;124m"[39m)

[1;31mSolverNotFoundError[0m: Solver with the requested features not available

